class Abonne {
  late String _firstName;
  late String _name;
  late String _postName;
  late String _dateOfBirth;
  late String _sex;
  late String _nationality;
  late String _electronicAddress;
  late String _countryOfResidence;
  late String _phoneNumber;
  late String _province;
  late String _town;
  late String _commune;
  late String _avenue;
  late String _number;
  late String _occupation;
  late String _identityPiece;
  late String _numberSeriesPiece;
}